var nama = "Ancela"
var body_path = "res://Assets/Images/UI/Karakter/Ancela/Dadam_Badan.png"

var normal_lurus_path = "res://Assets/Images/UI/Karakter/Ancela/Ancela_Normal.png"
var normal_path = "res://Assets/Images/UI/Karakter/Ancela/Ancela_Normal.png"
var lelah_path = "res://Assets/Images/UI/Karakter/Ancela/Ancela_Lelah.png"
var marah_path = "res://Assets/Images/UI/Karakter/Ancela/Ancela_Marah.png"
var sedih_path = "res://Assets/Images/UI/Karakter/Ancela/Ancela_Sedih.png"
var senang_path = "res://Assets/Images/UI/Karakter/Ancela/Ancela_Senang.png"
var terkejut_path = "res://Assets/Images/UI/Karakter/Ancela/Ancela_Normal.png"
