var nama = "Telepon"
var body_path = "res://Assets/Images/UI/Karakter/Telepon/Dadam_Badan.png"

var normal_lurus_path = "res://Assets/Images/UI/Karakter/Telepon/Telepon_Normal.png"
var normal_path = "res://Assets/Images/UI/Karakter/Telepon/Telepon_Normal.png"
var lelah_path = "res://Assets/Images/UI/Karakter/Telepon/Telepon_Lelah.png"
var marah_path = "res://Assets/Images/UI/Karakter/Telepon/Telepon_Marah.png"
var sedih_path = "res://Assets/Images/UI/Karakter/Telepon/Telepon_Sedih.png"
var senang_path = "res://Assets/Images/UI/Karakter/Telepon/Telepon_Senang.png"
var terkejut_path = "res://Assets/Images/UI/Karakter/Telepon/Telepon_Normal.png"
